export type TemplatePost = {
  title?: string;
  body: string;
  color?: string;
  linkUrl?: string;
  imageUrl?: string;
  author?: string;
  section?: string;
};

export type TemplateCategory = "Education" | "Work" | "Personal" | "Creative";
export type TemplateLayout = "grid" | "wall" | "stream" | "shelf";

export type Template = {
  id: string;
  name: string;
  description: string;
  category: TemplateCategory;
  layout: TemplateLayout;
  background: string;
  emoji: string;
  accent: string;
  tags: string[];
  sampleAuthor?: string;
  sections?: string[];
  posts: TemplatePost[];
};

const C = {
  yellow: "#fef9c3",
  amber: "#fef3c7",
  pink: "#fce7f3",
  rose: "#fee2e2",
  blue: "#dbeafe",
  sky: "#cffafe",
  green: "#dcfce7",
  mint: "#bbf7d0",
  lavender: "#ede9fe",
  periwinkle: "#e0e7ff",
  magenta: "#f5d0fe",
  orange: "#fed7aa",
  white: "#ffffff",
  cream: "#fffbeb",
};

export const TEMPLATES: Template[] = [
  // ─────────── EDUCATION ───────────
  {
    id: "class-announcements",
    name: "Class Announcements",
    description: "Post class updates, upcoming events, and important dates. Keep students and parents informed and engaged with class happenings.",
    category: "Education",
    layout: "grid",
    background: C.amber,
    emoji: "📣",
    accent: "from-amber-500 to-orange-500",
    tags: ["Communication", "Task management", "Grades K-12"],
    sampleAuthor: "Professor Crane",
    posts: [
      { title: "Math Test Next Week!", body: "Attention students! We have a math test scheduled for next Tuesday, covering chapters 4-6. Make sure to review the material and attend study sessions if needed.", color: C.amber, author: "Mr. Crane" },
      { title: "Field Trip Permission Slips Due", body: "Reminder for all students: Field trip permission slips for our visit to the Science Museum are due by Friday. Please hand them in to the main office.", color: C.blue, author: "Mr. Crane" },
      { title: "Science Fair Date Change", body: "Note to all: The science fair has been rescheduled from April 5th to April 12th. Adjust your calendars accordingly.", color: C.green, author: "Mr. Crane" },
      { title: "Parent-Teacher Conferences Next Month", body: "Parent-teacher conferences are set for the first week of next month. An email with scheduling details will be sent out soon.", color: C.lavender, author: "Mr. Crane" },
      { title: "Volunteer Opportunity: Beach Clean-up", body: "Those interested in community service, there's a beach clean-up event this Saturday. It's a great way to earn volunteer hours and help our environment!", color: C.sky, author: "Mr. Crane" },
      { title: "Art Showcase Evening", body: "Come and appreciate the artistic talents of our students at the art showcase evening next Thursday. Refreshments will be provided.", color: C.pink, author: "Mr. Crane" },
      { title: "Basketball Game Tonight", body: "Cheer for our school team at the home game tonight at 6 PM in the gymnasium. Show your school spirit!", color: C.orange, author: "Mr. Crane" },
      { title: "New School Website", body: "Our new school website is now live! Check it out for updated information, event calendars, and more.", color: C.yellow, author: "Mr. Crane" },
      { title: "Book Fair Next Week", body: "Exciting news! The annual book fair will be held in the school library all next week. It's a great opportunity to get some new reads!", color: C.rose, author: "Mr. Crane" },
      { title: "Debate Club Meeting", body: "The debate club will be meeting after school on Wednesday in Room 210. New members are always welcome!", color: C.mint, author: "Mr. Crane" },
    ],
  },
  {
    id: "about-us",
    name: "About Us",
    description: "A warm welcome board where every student answers a few playful prompts. One post per person. Great for the first week of class.",
    category: "Education",
    layout: "wall",
    background: "linear-gradient(135deg, #ede9fe 0%, #ddd6fe 50%, #c4b5fd 100%)",
    emoji: "😄",
    accent: "from-violet-500 to-fuchsia-500",
    tags: ["Communication", "Showcase", "Grades K-12"],
    sampleAuthor: "Ms. Patel",
    posts: [
      { title: "Welcome!", body: "Add a post and answer the four questions below. Add a photo if you like — paste, take with the camera, or generate one with AI.", color: "#ffffff", author: "Ms. Patel" },
      { title: "Sarah", body: "What's your name?\nSarah\n\nWho's your favorite celebrity?\nFlorence Pugh — bold actress, even better baker on Instagram.\n\nWhat's your favorite food?\nMy mum's biryani. Nothing else comes close.\n\nWhat's a fun fact about you?\nI can solve a Rubik's cube in under a minute (most days).", color: "#fce7f3", author: "Sarah" },
      { title: "Marcus", body: "What's your name?\nMarcus\n\nWho's your favorite celebrity?\nDonald Glover — actor, musician, writer, all of it.\n\nWhat's your favorite food?\nKorean fried chicken. The double-fry is non-negotiable.\n\nWhat's a fun fact about you?\nI've been to 14 countries but never crossed a single border by land. Always flying.", color: "#dbeafe", author: "Marcus" },
      { title: "Priya", body: "What's your name?\nPriya\n\nWho's your favorite celebrity?\nMalala Yousafzai. Her TED talk made me cry in class.\n\nWhat's your favorite food?\nMasala dosa from a tiny place near my grandma's house.\n\nWhat's a fun fact about you?\nI play the violin. I've been at it since I was 6 — mostly for fun, but I once played at a wedding for tips.", color: "#dcfce7", author: "Priya" },
      { title: "Diego", body: "What's your name?\nDiego\n\nWho's your favorite celebrity?\nLionel Messi. Obviously.\n\nWhat's your favorite food?\nMilanesa with mashed potato. Pure comfort food.\n\nWhat's a fun fact about you?\nI'm an amateur boxer. 3 fights, 2 wins. The third was a bad day.", color: "#fef3c7", author: "Diego" },
      { title: "Léa", body: "What's your name?\nLéa\n\nWho's your favorite celebrity?\nGreta Gerwig. Lady Bird is my comfort movie.\n\nWhat's your favorite food?\nHomemade gnocchi. The kind that takes all afternoon.\n\nWhat's a fun fact about you?\nI grew up trilingual (French, English, Vietnamese) but my best language is sarcasm.", color: "#fed7aa", author: "Léa" },
      { title: "Kenji", body: "What's your name?\nKenji\n\nWho's your favorite celebrity?\nHayao Miyazaki — the Studio Ghibli films raised me.\n\nWhat's your favorite food?\nA perfectly soft-boiled ramen egg. Whole meal around it.\n\nWhat's a fun fact about you?\nI've been keeping a diary every single day for 4 years. Just one paragraph.", color: "#cffafe", author: "Kenji" },
    ],
  },
  {
    id: "class-discussion",
    name: "Class Discussion",
    description: "Spark thoughtful conversation around a question. Students post responses, build on each other's ideas, and learn together.",
    category: "Education",
    layout: "stream",
    background: C.blue,
    emoji: "💬",
    accent: "from-blue-500 to-indigo-500",
    tags: ["Discussion", "Lessons", "Grades 3-12"],
    sampleAuthor: "Ms. Patel",
    posts: [
      { title: "This week's question", body: "If you could solve one global challenge in your lifetime, what would it be — and what's the first small step you'd take this year?", color: C.blue, author: "Ms. Patel" },
      { title: "How to participate", body: "• Post your response below\n• Read at least three other replies\n• Reply with a thoughtful follow-up to one classmate\n• Cite a source if you can", color: C.white, author: "Ms. Patel" },
      { title: "Reducing food waste in cities", body: "Around 30% of food worldwide gets wasted while people go hungry. I'd want to start a community fridge network at our school — a small one, where families can leave or take fresh food no questions asked.", color: C.green, author: "Maya R." },
      { title: "Mental health in young people", body: "Anxiety and depression rates have doubled in our age group since 2010. I'd push for mandatory mental-health check-ins in schools, the same way we get vision tests. First step: write to my school board.", color: C.lavender, author: "James K." },
      { title: "Ocean plastic pollution", body: "By 2050 there could be more plastic than fish in the sea by weight. I'd start a refill culture — bring-your-own everything. First step: a refill station at our school cafeteria.", color: C.sky, author: "Aiko T." },
      { title: "Loneliness and isolation", body: "1 in 4 adults reports feeling lonely. I'd build community spaces in every neighborhood — like the third places we used to have. First step: organize one block party this summer.", color: C.pink, author: "Diego S." },
    ],
  },
  {
    id: "kwl-chart",
    name: "KWL Chart",
    description: "Track what students Know, Wonder about, and have Learned in three columns. Tap prior knowledge before a unit, see growth after.",
    category: "Education",
    layout: "shelf",
    background: C.yellow,
    emoji: "📚",
    accent: "from-yellow-500 to-amber-500",
    tags: ["Lessons", "Reflection", "Grades K-12"],
    sections: ["K — What I Know", "W — What I Wonder", "L — What I Learned"],
    posts: [
      { body: "Lava is hot. Volcanoes are mountains. They erupt sometimes.", color: C.green, author: "Mira", section: "K — What I Know" },
      { body: "Some volcanoes are underwater.", color: C.green, author: "Theo", section: "K — What I Know" },
      { body: "There's a famous one in Hawaii.", color: C.green, author: "Léa", section: "K — What I Know" },
      { body: "Ash from volcanoes can travel really far.", color: C.green, author: "Sam", section: "K — What I Know" },
      { body: "How do scientists know when one will erupt?", color: C.amber, author: "Mira", section: "W — What I Wonder" },
      { body: "Why do some have explosive eruptions and others just ooze lava slowly?", color: C.amber, author: "Sam", section: "W — What I Wonder" },
      { body: "Are there volcanoes on other planets?", color: C.amber, author: "Léa", section: "W — What I Wonder" },
      { body: "Could we use the heat from volcanoes for energy?", color: C.amber, author: "Theo", section: "W — What I Wonder" },
      { body: "Geologists track tiny earthquakes and gas emissions to predict eruptions.", color: C.blue, author: "Mira", section: "L — What I Learned" },
      { body: "Olympus Mons on Mars is the largest volcano in the solar system.", color: C.blue, author: "Sam", section: "L — What I Learned" },
      { body: "Iceland gets ~85% of its heating from geothermal — basically harnessing volcanoes.", color: C.blue, author: "Léa", section: "L — What I Learned" },
    ],
  },
  {
    id: "brainstorm",
    name: "Brainstorm",
    description: "Capture every idea, no matter how wild. Cluster, vote, and refine later.",
    category: "Education",
    layout: "wall",
    background: C.amber,
    emoji: "💡",
    accent: "from-amber-500 to-orange-500",
    tags: ["Brainstorming", "Lessons", "Communication"],
    sampleAuthor: "Mr. Lee",
    posts: [
      { title: "The challenge", body: "How might we make our school a more welcoming place for new students in their first month?", color: C.amber, author: "Mr. Lee" },
      { body: "Buddy system — match every new student with a guide from the same grade for the first 30 days.", color: C.green, author: "Anya" },
      { body: "Welcome lunch in week 1 — small group, free pizza, no agenda except getting to know each other.", color: C.pink, author: "Tomás" },
      { body: "Self-guided campus map with photos and short videos of each room. Students could film it themselves.", color: C.lavender, author: "Priya" },
      { body: "Anonymous \"first impression\" suggestion box — collect feedback in week 2.", color: C.sky, author: "Leo" },
      { body: "School-wide scavenger hunt on day one. Mixed teams. Prizes for everyone.", color: C.orange, author: "Hannah" },
      { body: "Wild idea: Time-capsule letter — every new student writes one to their future self, opened at graduation.", color: C.yellow, author: "Marcus" },
      { body: "Buddy teachers — pair every newcomer with a teacher mentor outside their classes.", color: C.mint, author: "Sara" },
      { body: "First-week journals — five short prompts, voluntary, anonymous if they want.", color: C.rose, author: "Kenji" },
    ],
  },
  {
    id: "pros-and-cons",
    name: "Pros & Cons",
    description: "Three columns to weigh both sides of any decision: For, Against, and Open Questions. Great for class debates or group decisions.",
    category: "Education",
    layout: "shelf",
    background: C.green,
    emoji: "⚖️",
    accent: "from-green-500 to-emerald-500",
    tags: ["Discussion", "Reflection", "Lessons"],
    sections: ["✅ For", "❌ Against", "❓ Questions"],
    posts: [
      { title: "Topic", body: "Should our school require students to take a coding class to graduate?", color: C.lavender, author: "Ms. Khan" },
      { body: "Coding teaches problem-solving that transfers to every subject.", color: C.green, author: "Anya", section: "✅ For" },
      { body: "Software is in every job now. Even non-tech workers need to understand the basics.", color: C.green, author: "Diego", section: "✅ For" },
      { body: "Builds confidence with computers — closes the digital divide.", color: C.green, author: "Sara", section: "✅ For" },
      { body: "Forces students who hate it through it, when they could be doing music or art.", color: C.rose, author: "Kenji", section: "❌ Against" },
      { body: "Schools don't have qualified teachers. A bad mandatory class is worse than none.", color: C.rose, author: "Hannah", section: "❌ Against" },
      { body: "AI is going to write code. Maybe we should teach what AI can't.", color: C.rose, author: "Tomás", section: "❌ Against" },
      { body: "Which language? Python is friendly but JavaScript is more useful in real jobs.", color: C.amber, author: "Leo", section: "❓ Questions" },
      { body: "Could it be a half-credit instead of full?", color: C.amber, author: "Priya", section: "❓ Questions" },
      { body: "Would we lose an art or music slot to make room?", color: C.amber, author: "Marcus", section: "❓ Questions" },
    ],
  },
  {
    id: "compare-contrast",
    name: "Compare & Contrast",
    description: "Three columns: Topic A · What's the same · Topic B. Perfect for literature pairings, historical events, or scientific concepts.",
    category: "Education",
    layout: "shelf",
    background: C.lavender,
    emoji: "🔀",
    accent: "from-violet-500 to-fuchsia-500",
    tags: ["Lessons", "Reflection", "Grades 3-12"],
    sections: ["The Great Gatsby", "Both", "The Catcher in the Rye"],
    posts: [
      { body: "Set in 1920s — jazz age decadence", color: C.amber, author: "Maya", section: "The Great Gatsby" },
      { body: "Narrated by Nick Carraway, an outsider", color: C.amber, author: "Felix", section: "The Great Gatsby" },
      { body: "Theme: chasing an unreachable dream", color: C.amber, author: "Aria", section: "The Great Gatsby" },
      { body: "Ends in tragedy and disillusionment", color: C.amber, author: "Liam", section: "The Great Gatsby" },
      { body: "American novel · 20th century", color: C.lavender, author: "Maya", section: "Both" },
      { body: "Outsider protagonists who don't fit in", color: C.lavender, author: "Felix", section: "Both" },
      { body: "Critique of post-war American society", color: C.lavender, author: "Aria", section: "Both" },
      { body: "Themes of loneliness and false fronts", color: C.lavender, author: "Liam", section: "Both" },
      { body: "Set in 1950s — post-war anxiety", color: C.pink, author: "Maya", section: "The Catcher in the Rye" },
      { body: "Narrated by Holden Caulfield directly", color: C.pink, author: "Felix", section: "The Catcher in the Rye" },
      { body: "Theme: holding onto childhood innocence", color: C.pink, author: "Aria", section: "The Catcher in the Rye" },
      { body: "Ends with ambiguous redemption", color: C.pink, author: "Liam", section: "The Catcher in the Rye" },
    ],
  },
  {
    id: "reading-list",
    name: "Reading List",
    description: "Build a shared shelf of books to read or recommend, with short reviews and cover notes from classmates.",
    category: "Education",
    layout: "wall",
    background: C.cream,
    emoji: "📖",
    accent: "from-orange-500 to-red-500",
    tags: ["Showcase", "Communication", "Grades 3-12"],
    posts: [
      { title: "Atomic Habits — James Clear", body: "Practical, no-fluff guide to building habits one tiny step at a time. The 1% better idea changed how I study. Short chapters — perfect bedtime read.", color: C.amber, author: "Aria" },
      { title: "Sapiens — Yuval Noah Harari", body: "A sweeping history of our species in 400 pages. The chapter on agriculture being humanity's biggest mistake will mess with your head in a good way.", color: C.green, author: "Felix" },
      { title: "The Pragmatic Programmer", body: "If you're getting into coding, read this. It's not a how-to — it's about how to think like an engineer. The DRY principle alone saved me hours.", color: C.blue, author: "Nadia" },
      { title: "Educated — Tara Westover", body: "Memoir of a girl who grew up off-grid and earned a Cambridge PhD. Reads like a thriller, but real. Hard to put down.", color: C.pink, author: "Liam" },
      { title: "Project Hail Mary — Andy Weir", body: "Sci-fi from the author of The Martian. A one-man mission to save humanity, with a very unexpected partner. Funny, smart, hopeful.", color: C.lavender, author: "Ines" },
      { title: "The House in the Cerulean Sea", body: "Cozy fantasy about a magical orphanage and a buttoned-up caseworker. The kind of book that makes you want to hug it when you finish.", color: C.sky, author: "Ravi" },
    ],
  },
  {
    id: "qa-board",
    name: "Q&A Board",
    description: "Anonymous questions, openly answered. Removes the fear of asking and builds a searchable archive of answers over time.",
    category: "Education",
    layout: "stream",
    background: C.green,
    emoji: "❓",
    accent: "from-emerald-500 to-teal-500",
    tags: ["Communication", "Discussion", "Higher ed"],
    sampleAuthor: "Course Staff",
    posts: [
      { title: "How this works", body: "Drop any question — about content, logistics, life. Post anonymously if you'd like. We answer within 24 hours and pin the most useful threads.", color: C.green, author: "Course Staff" },
      { title: "Q: When is the next assignment due?", body: "Asked by: anonymous", color: C.amber },
      { title: "A:", body: "Friday at 11:59 PM. Late submissions accepted with a 10% penalty until Monday. After that, no credit unless you have an approved extension.", color: C.blue, author: "Course Staff" },
      { title: "Q: I'm completely stuck on problem 3. Where do I even start?", body: "Asked by: anonymous", color: C.amber },
      { title: "A:", body: "Try working backwards from the answer for a similar smaller case (n=2). Pattern usually becomes clear. Office hours Wed 3-5 if you want to walk through it together.", color: C.blue, author: "Course Staff" },
      { title: "Q: Can we use AI tools on the project?", body: "Asked by: anonymous", color: C.amber },
      { title: "A:", body: "Yes for ideation and debugging. No for generating the final write-up. Always cite which tool you used and how. Honest disclosure is better than getting caught.", color: C.blue, author: "Course Staff" },
    ],
  },
  {
    id: "three-two-one",
    name: "3-2-1 Summary",
    description: "End a lesson with a quick reflection: 3 things students learned, 2 they found interesting, 1 question they still have.",
    category: "Education",
    layout: "stream",
    background: C.lavender,
    emoji: "🎯",
    accent: "from-violet-500 to-purple-500",
    tags: ["Reflection", "Assessment", "Lessons"],
    posts: [
      { title: "How to use this", body: "After today's lesson, post once with three sections: 3 things you learned · 2 things that surprised or interested you · 1 question you still have.", color: C.lavender },
      { title: "Mira's 3-2-1 — Photosynthesis", body: "3 learned: chlorophyll absorbs red and blue light; oxygen is a by-product, not the goal; sunlight powers the whole thing.\n\n2 interesting: plants in the deep ocean use a different pigment; some plants are partially carnivorous if soil nutrients are low.\n\n1 question: do all leaves do photosynthesis at the same rate?", color: C.green, author: "Mira" },
      { title: "Theo's 3-2-1", body: "3 learned: the Calvin cycle happens at night; ATP is the energy currency; CO2 enters through stomata.\n\n2 interesting: trees can communicate through fungal networks; cacti do photosynthesis at night to save water.\n\n1 question: could we engineer faster photosynthesis to grow food in less space?", color: C.amber, author: "Theo" },
    ],
  },
  {
    id: "show-what-you-know",
    name: "Show What You Know",
    description: "Four-quadrant formative assessment: Define · Example · Picture · Question. Students post in the section that matches their thinking.",
    category: "Education",
    layout: "shelf",
    background: C.sky,
    emoji: "✏️",
    accent: "from-sky-500 to-blue-500",
    tags: ["Assessment", "Lessons", "Grades K-12"],
    sections: ["Define it", "Example it", "Picture it", "Question it"],
    posts: [
      { title: "What is photosynthesis?", body: "Plants making their own food using sunlight, water, and carbon dioxide.", color: C.sky, author: "Aria", section: "Define it" },
      { title: "What is symbiosis?", body: "Two organisms living closely together, where at least one benefits.", color: C.sky, author: "Felix", section: "Define it" },
      { title: "Symbiosis example", body: "Clownfish and sea anemones — fish gets protection, anemone gets cleaned.", color: C.green, author: "Felix", section: "Example it" },
      { title: "Photosynthesis example", body: "The big oak tree on the playground turns sunlight into all the leaves and acorns.", color: C.green, author: "Aria", section: "Example it" },
      { title: "Photosynthesis sketch", body: "[Sketch description: sun → leaf → arrows showing CO₂ in, O₂ out, sugar made inside]", color: C.amber, author: "Mira", section: "Picture it" },
      { title: "Symbiosis sketch", body: "[Sketch description: anemone with tentacles, clownfish nestled inside, arrows showing protection ↔ cleaning]", color: C.amber, author: "Theo", section: "Picture it" },
      { body: "Do plants stop photosynthesis at night, or just slow down?", color: C.pink, author: "Léa", section: "Question it" },
      { body: "Can two species in symbiosis ever break apart and survive?", color: C.pink, author: "Sam", section: "Question it" },
    ],
  },

  // ─────────── WORK ───────────
  {
    id: "sprint-board",
    name: "Sprint Board",
    description: "A simple Kanban: Backlog · In progress · In review · Done. Drag posts between columns as work moves forward.",
    category: "Work",
    layout: "shelf",
    background: "linear-gradient(135deg, #e0e7ff 0%, #ddd6fe 50%, #c4b5fd 100%)",
    emoji: "📋",
    accent: "from-indigo-500 to-violet-500",
    tags: ["Task management", "Team", "Planning"],
    sections: ["Backlog", "In progress", "In review", "Done"],
    posts: [
      { title: "Add 2FA support", body: "Email + authenticator app. Block login until verified for new accounts.", color: C.blue, author: "Priya", section: "Backlog" },
      { title: "Improve empty states", body: "Every \"no data\" screen should have a hint about how to add data.", color: C.lavender, author: "Sam", section: "Backlog" },
      { title: "Customer.io email warmup", body: "Domain warming for new sender. ~14 days of gradual volume.", color: C.amber, author: "Maya", section: "Backlog" },
      { title: "Onboarding redesign — frontend", body: "Implementing the v2 flow behind a feature flag. ~70% done.", color: C.green, author: "Diego", section: "In progress" },
      { title: "Auth refactor", body: "Pulling auth out of the monolith into its own service. Pair with Priya.", color: C.green, author: "Anya", section: "In progress" },
      { title: "Pricing page A/B", body: "Variant B (annual default) is winning by 11%. Need 2 more weeks of data.", color: C.pink, author: "Jordan", section: "In review" },
      { title: "Mobile nav fix", body: "PR open. Awaiting one more review.", color: C.pink, author: "Maya", section: "In review" },
      { title: "Slack integration", body: "Shipped Tuesday. 47 workspaces installed in first 48h.", color: C.mint, author: "Diego", section: "Done" },
      { title: "Search index migration", body: "Cut search latency from 800ms p95 to 90ms.", color: C.mint, author: "Priya", section: "Done" },
      { title: "Error boundary on dashboard", body: "Fixes the white-screen-of-death we were seeing in Sentry.", color: C.mint, author: "Sam", section: "Done" },
    ],
  },
  {
    id: "group-project",
    name: "Group Project Tasks",
    description: "Track who's doing what on a group project. Three columns for the whole flow, posts tagged with names.",
    category: "Work",
    layout: "shelf",
    background: C.mint,
    emoji: "👥",
    accent: "from-emerald-500 to-green-500",
    tags: ["Task management", "Team", "Lessons"],
    sections: ["To do", "Doing", "Done"],
    posts: [
      { title: "Research: history of paper money", body: "Find 5 reliable sources, summarize each in 2 sentences.\nAssigned: Mira · Due: Thu", color: C.amber, author: "Mira", section: "To do" },
      { title: "Survey design (50 responses)", body: "10 questions on spending habits. Distribute through class WhatsApp.\nAssigned: Theo · Due: Fri", color: C.amber, author: "Theo", section: "To do" },
      { title: "Final slides", body: "Combine sections into one deck. Two run-throughs before Tuesday.\nAssigned: All · Due: Mon", color: C.amber, author: "Sam", section: "To do" },
      { title: "Interview a small business owner", body: "30 min, recorded. Ask about their cash vs digital ratio over time.\nAssigned: Léa · Due: this week", color: C.lavender, author: "Léa", section: "Doing" },
      { title: "Section 2: digital wallets in Asia", body: "Write 800 words. Sources from Singapore, India, China.\nAssigned: Sam · Due: Sat", color: C.lavender, author: "Sam", section: "Doing" },
      { title: "Pick the project topic", body: "Settled on \"Has cash become obsolete?\" — agreed Wednesday.", color: C.green, author: "All", section: "Done" },
      { title: "Outline the deck", body: "5 sections, 2 slides each. Locked in.", color: C.green, author: "Mira", section: "Done" },
      { title: "Set up the shared drive", body: "Folder structure done. Everyone has edit access.", color: C.green, author: "Theo", section: "Done" },
    ],
  },
  {
    id: "project-plan",
    name: "Project Plan",
    description: "Map out phases, owners, milestones, and risks for a project. A living plan that lets your team see the whole arc.",
    category: "Work",
    layout: "stream",
    background: C.periwinkle,
    emoji: "🗂️",
    accent: "from-indigo-500 to-violet-500",
    tags: ["Planning", "Task management", "Team"],
    posts: [
      { title: "Project: Customer Onboarding Redesign", body: "Goal: cut new-user activation time from 12 days to 4. Stakeholders: Growth, Product, Customer Success. Target ship: end of Q3.", color: C.periwinkle, author: "PM" },
      { title: "Phase 1 — Discover (2 weeks)", body: "10 user interviews · funnel analytics · audit of current emails and screens.\nOwner: Priya · Status: in progress (5/10 interviews done)", color: C.blue },
      { title: "Phase 2 — Design (3 weeks)", body: "Wireframes for new flow · 2 rounds of usability testing · final mocks signed off.\nOwner: Sam · Status: not started", color: C.lavender },
      { title: "Phase 3 — Build (4 weeks)", body: "Frontend rebuild of onboarding flow · email sequence in Customer.io · feature flag rollout.\nOwner: Eng team · Status: not started", color: C.green },
      { title: "Phase 4 — Launch (1 week)", body: "Internal beta · 10% rollout · 50% rollout · full ship. Monitor activation rate daily.\nOwner: Jordan · Status: not started", color: C.amber },
      { title: "Risks & mitigations", body: "• Interview no-shows → recruit 15 to land 10\n• Email deliverability → warm up new domain now\n• Scope creep on the build → ship behind a flag, defer non-critical to v2", color: C.rose },
    ],
  },
  {
    id: "meeting-agenda",
    name: "Meeting Agenda",
    description: "A clear agenda before a meeting, decisions captured during, action items right after. One source of truth.",
    category: "Work",
    layout: "stream",
    background: C.sky,
    emoji: "📅",
    accent: "from-sky-500 to-blue-500",
    tags: ["Planning", "Communication", "Team"],
    posts: [
      { title: "Weekly Product Sync — Tuesday 10:00", body: "Attendees: Priya, Sam, Jordan, Maya · Notetaker: Sam · Decision-maker: Priya", color: C.sky, author: "Sam" },
      { title: "1. Updates (10 min)", body: "Each person: one win, one blocker, one ask. Keep it under 90 seconds.", color: C.white },
      { title: "2. Onboarding redesign — review wireframes (20 min)", body: "Sam walks through v2 wireframes. Decision needed: which flow do we test first — guided tour vs. progressive disclosure?", color: C.blue, author: "Sam" },
      { title: "3. Q3 OKR check-in (15 min)", body: "Are we on track? What's at risk? What's been deprioritized that we should re-examine?", color: C.lavender, author: "Priya" },
      { title: "4. Open floor (5 min)", body: "Anything urgent we missed?", color: C.amber },
      { title: "Decisions made", body: "✓ Test guided tour first; progressive disclosure as the v2 if needed\n✓ Pull the email sprint forward by one week\n✓ Drop the dashboard side-quest for now", color: C.green },
      { title: "Action items", body: "→ Sam: ship test plan by Thursday\n→ Priya: update Q3 OKRs in Notion by Friday\n→ Jordan: book user interviews for next Tuesday", color: C.pink },
    ],
  },
  {
    id: "retrospective",
    name: "Sprint Retrospective",
    description: "Four columns: what went well, what didn't, what to try, and shout-outs. Run it after every sprint.",
    category: "Work",
    layout: "shelf",
    background: C.lavender,
    emoji: "🔄",
    accent: "from-violet-500 to-fuchsia-500",
    tags: ["Reflection", "Team", "Planning"],
    sections: ["👍 Went well", "👎 Didn't go well", "💡 Try next time", "🙌 Shout-outs"],
    posts: [
      { body: "Daily standups were tight — under 10 min all week.", color: C.green, author: "Anya", section: "👍 Went well" },
      { body: "Pair programming on the auth refactor caught two bugs early. Worth keeping for hard problems.", color: C.green, author: "Diego", section: "👍 Went well" },
      { body: "Customer demo Thursday went better than expected. They asked when can they pay us.", color: C.green, author: "Priya", section: "👍 Went well" },
      { body: "PR reviews piled up over the weekend. Felt like Monday was just catching up.", color: C.rose, author: "Sam", section: "👎 Didn't go well" },
      { body: "Three context switches in one day on Tuesday. Lost the morning to meetings I didn't need to be in.", color: C.rose, author: "Jordan", section: "👎 Didn't go well" },
      { body: "Staging environment was down for 4 hours mid-week. No one owned figuring it out.", color: C.rose, author: "Maya", section: "👎 Didn't go well" },
      { body: "Async review hour: 3-4 PM daily, anyone reviewing then. Test for two weeks.", color: C.amber, author: "Sam", section: "💡 Try next time" },
      { body: "Optional meetings clearly marked. Default to no, opt in if relevant. PM owns the trim.", color: C.amber, author: "Jordan", section: "💡 Try next time" },
      { body: "Big thanks to Maya for staying late to debug staging — and writing it up so next time we don't lose hours.", color: C.pink, author: "Anya", section: "🙌 Shout-outs" },
      { body: "Diego's ticket triage on Monday cleared 14 stale issues. Underrated work.", color: C.pink, author: "Priya", section: "🙌 Shout-outs" },
    ],
  },
  {
    id: "idea-backlog",
    name: "Idea Backlog",
    description: "Park every idea so none are lost. Color-code by theme. Sort and prioritize when you're ready.",
    category: "Work",
    layout: "wall",
    background: C.yellow,
    emoji: "📌",
    accent: "from-yellow-500 to-amber-500",
    tags: ["Brainstorming", "Planning"],
    posts: [
      { body: "Onboarding email series — five emails over the first two weeks teaching the most-used features.", color: C.blue, author: "Maya" },
      { body: "Public roadmap page — let users see what's coming and vote on priorities.", color: C.green, author: "Priya" },
      { body: "Annual user conference — one day, 200 people, in-person. Big bet but our community would love it.", color: C.orange, author: "Jordan" },
      { body: "Weekly digest of community wins. Lightweight, hand-written, ships every Friday.", color: C.pink, author: "Sam" },
      { body: "Better empty states across the app. Right now they all just say \"No data\". We can do better.", color: C.lavender, author: "Diego" },
      { body: "Mobile app — native iOS first. Most of our users use the web on mobile already.", color: C.sky, author: "Maya" },
      { body: "Referral program — give one month free for each friend invited.", color: C.amber, author: "Priya" },
      { body: "Keyboard shortcuts. We have none. Power users keep asking for them.", color: C.mint, author: "Anya" },
    ],
  },
  {
    id: "team-intros",
    name: "Team Introductions",
    description: "Help a team get to know each other beyond their job titles. Great for new hires, remote teams, or new project squads.",
    category: "Work",
    layout: "grid",
    background: C.mint,
    emoji: "👋",
    accent: "from-emerald-500 to-green-500",
    tags: ["Communication", "Team", "Showcase"],
    posts: [
      { title: "Hi, I'm Sam", body: "Role: Product Designer\nBased in: Singapore (UTC+8)\nSuperpower: Turning chaos into wireframes\nFun fact: I bake sourdough every weekend — happy to share starter", color: C.mint, author: "Sam" },
      { title: "Hi, I'm Priya", body: "Role: Backend Engineer\nBased in: Bangalore (UTC+5:30)\nSuperpower: Making Postgres go brrr\nFun fact: Trained as a classical violinist before pivoting to code", color: C.lavender, author: "Priya" },
      { title: "Hi, I'm Jordan", body: "Role: Product Manager\nBased in: Toronto (UTC-5)\nSuperpower: Saying no to scope creep\nFun fact: I've finished 47 of the 50 US states. Working on Idaho next year.", color: C.amber, author: "Jordan" },
      { title: "Hi, I'm Maya", body: "Role: Frontend Engineer\nBased in: Berlin (UTC+1)\nSuperpower: CSS that actually works on every browser\nFun fact: I speak five languages, four of which I learned as an adult", color: C.pink, author: "Maya" },
      { title: "Hi, I'm Diego", body: "Role: Customer Success\nBased in: Mexico City (UTC-6)\nSuperpower: Turning angry tickets into happy renewals\nFun fact: I'm a competitive amateur boxer", color: C.sky, author: "Diego" },
      { title: "Hi, I'm Anya", body: "Role: Engineering Manager\nBased in: London (UTC+0)\nSuperpower: 1:1s that don't feel like they're 1:1s\nFun fact: I host a podcast about board game design", color: C.rose, author: "Anya" },
    ],
  },
  {
    id: "okr-tracker",
    name: "OKR Tracker",
    description: "Write objectives and key results, track them weekly. Color-code by status: green on track, amber at risk, red off track.",
    category: "Work",
    layout: "stream",
    background: C.orange,
    emoji: "🎯",
    accent: "from-orange-500 to-rose-500",
    tags: ["Planning", "Task management", "Team"],
    posts: [
      { title: "Q3 — Objective 1: Become the team people recommend", body: "Why: word-of-mouth is our cheapest growth channel and our best signal. If we earn it, the rest gets easier.", color: C.orange, author: "Priya" },
      { title: "KR 1.1 · NPS from 32 → 50", body: "Status: 🟢 on track (currently 41)\nNext step: ship onboarding redesign by week 8", color: C.green },
      { title: "KR 1.2 · 25% of new signups come from referrals", body: "Status: 🟡 at risk (currently 14%)\nNext step: launch referral program in week 6", color: C.amber },
      { title: "KR 1.3 · Median time-to-value under 10 minutes", body: "Status: 🟢 on track (currently 11 min, was 23)\nNext step: holding pattern, monitor", color: C.green },
      { title: "Q3 — Objective 2: Make the platform feel fast", body: "Why: speed isn't a feature, it's a tax on every other feature. Slow apps die slowly.", color: C.orange, author: "Anya" },
      { title: "KR 2.1 · p95 page load under 1.5s", body: "Status: 🔴 off track (currently 3.2s)\nNext step: dedicate two engineers next sprint", color: C.rose },
      { title: "KR 2.2 · Zero pages with > 5s LCP", body: "Status: 🟡 at risk (4 pages still over 5s)\nNext step: image audit + lazy-load pass", color: C.amber },
    ],
  },

  // ─────────── PERSONAL ───────────
  {
    id: "goals-board",
    name: "Goals Board",
    description: "Three columns for three time-horizons: This week · This month · This year. Move them across as you finish.",
    category: "Personal",
    layout: "shelf",
    background: C.pink,
    emoji: "🏆",
    accent: "from-rose-500 to-pink-500",
    tags: ["Planning", "Personal", "Reflection"],
    sections: ["This week", "This month", "This year"],
    posts: [
      { body: "Run 3x. 5K each.", color: C.green, section: "This week" },
      { body: "Finish chapter 4 of the novel I'm reading.", color: C.green, section: "This week" },
      { body: "Reach out to two old friends I've lost touch with.", color: C.green, section: "This week" },
      { body: "Cook dinner at home Mon–Fri. No takeout.", color: C.green, section: "This week" },
      { body: "Ship the personal project I've been on for two months.", color: C.amber, section: "This month" },
      { body: "Run 50K total. Build base before the half-marathon training.", color: C.amber, section: "This month" },
      { body: "Read 3 books — one fiction, one on craft, one wild card.", color: C.amber, section: "This month" },
      { body: "Save 20% of this month's pay before anything else.", color: C.amber, section: "This month" },
      { body: "Run a half-marathon. Sub-2:00.", color: C.lavender, section: "This year" },
      { body: "Visit Japan in cherry blossom season.", color: C.lavender, section: "This year" },
      { body: "Read 24 books. Track them in one place.", color: C.lavender, section: "This year" },
      { body: "Learn enough Japanese to order food without pointing.", color: C.lavender, section: "This year" },
    ],
  },
  {
    id: "bucket-list",
    name: "Bucket List",
    description: "All the experiences, places, and people you'd love your life to include. Add as you dream them up. Cross off as you do them.",
    category: "Personal",
    layout: "wall",
    background: "linear-gradient(135deg, #fef3c7 0%, #fce7f3 50%, #ddd6fe 100%)",
    emoji: "🌟",
    accent: "from-rose-500 to-pink-500",
    tags: ["Personal", "Showcase"],
    posts: [
      { title: "See the northern lights", body: "Iceland or Norway in February. Best chance of clear skies + active aurora. Stay 4 nights to maximize odds.", color: C.sky, author: "me" },
      { title: "Run a half-marathon", body: "Train for 12 weeks. Local race, finish under 2 hours. Sign up early so I can't back out.", color: C.green, author: "me" },
      { title: "Learn to surf properly", body: "Bali or Portugal. 5-day intensive course. Goal: catch a green wave by myself, no instructor push.", color: C.amber, author: "me" },
      { title: "Write a novel", body: "Even a short one. 50,000 words in a notebook is enough. Could be terrible. The point is finishing.", color: C.lavender, author: "me" },
      { title: "Visit Japan in cherry blossom season", body: "Late March / early April. Kyoto + Tokyo + a small mountain town. Travel by train, not plane.", color: C.pink, author: "me" },
      { title: "Cook through a cookbook", body: "Pick one. Make every recipe over 12 months. Salt Fat Acid Heat or Vietnamese Food Any Day.", color: C.orange, author: "me" },
      { title: "Speak passable Spanish", body: "Define passable: hold a 30-min conversation about anything. Try Pimsleur 30 min/day.", color: C.rose, author: "me" },
      { title: "Sleep under the stars in the desert", body: "Wadi Rum, Atacama, or Joshua Tree. No tent. Just a bivvy and a sky full of stars.", color: C.yellow, author: "me" },
    ],
  },
  {
    id: "about-me",
    name: "About Me",
    description: "A friendly intro for classmates, new teammates, or new friends. Share who you are, not just what you do.",
    category: "Personal",
    layout: "grid",
    background: "linear-gradient(135deg, #ede9fe 0%, #ddd6fe 50%, #c4b5fd 100%)",
    emoji: "🙋",
    accent: "from-violet-500 to-purple-500",
    tags: ["Personal", "Showcase", "Communication"],
    posts: [
      { title: "Hi, I'm…", body: "Afzaana, from Singapore. Engineering student at NTU, currently figuring out what I want to be when I grow up. Big fan of late-night coding sessions and very strong tea.", color: C.lavender },
      { title: "What I'm into", body: "Building little side projects, lo-fi hip hop, walking with no destination, anime that makes you cry, mechanical keyboards, learning languages badly.", color: C.pink },
      { title: "Currently reading", body: "Project Hail Mary by Andy Weir. About 60% in. Already cried twice.", color: C.amber },
      { title: "A goal I'm working on", body: "Ship one personal project a month for a year. This Padlet clone counts as project #1.", color: C.green },
      { title: "Where I've lived", body: "Singapore (born here) → 6 months on exchange in Helsinki → back home. The contrast made me appreciate both.", color: C.sky },
      { title: "Fun fact", body: "I can't whistle. Tried for 20 years. Doctors say my mouth shape just isn't right for it. I've made peace with it.", color: C.rose },
    ],
  },
  {
    id: "daily-journal",
    name: "Daily Journal",
    description: "A gentle daily check-in with yourself. Three minutes a day, more clarity over time.",
    category: "Personal",
    layout: "stream",
    background: C.amber,
    emoji: "📓",
    accent: "from-amber-500 to-yellow-500",
    tags: ["Personal", "Reflection"],
    posts: [
      { title: "Tuesday, May 1", body: "Honestly? Tired. Slept badly. But got up, walked, and felt better by 9am. Caffeine is a miracle drug.", color: C.amber },
      { title: "Three things I'm grateful for", body: "1. The way morning light hits my desk\n2. My friend M sending me a meme that made me laugh out loud\n3. A working hot shower", color: C.green },
      { title: "One small win", body: "Finally fixed the bug I've been chasing for three days. The answer was a missing await. Of course.", color: C.pink },
      { title: "On my mind", body: "Worried about exams next week. The plan is fine, the execution is the issue — I keep getting distracted. Phone in another room from 9am tomorrow.", color: C.lavender },
      { title: "Tomorrow I will…", body: "Wake at 7. 30 min of focused study before breakfast. Then go from there. Don't try to plan the whole day, just the first hour.", color: C.sky },
    ],
  },
  {
    id: "recipe-collection",
    name: "Recipe Collection",
    description: "Save the dishes you actually want to cook again. Add notes after the second time so you remember what to tweak.",
    category: "Personal",
    layout: "wall",
    background: C.orange,
    emoji: "🍳",
    accent: "from-orange-500 to-red-500",
    tags: ["Personal", "Showcase"],
    posts: [
      { title: "One-pan miso salmon", body: "20 min · serves 2\n\n2 salmon fillets · 1 tbsp white miso · 1 tbsp honey · 1 tsp soy · cooked rice · greens.\n\nMix miso/honey/soy, brush on salmon. Bake 200°C for 12 min. Serve over rice with quick-sautéed greens.\n\nNote: skip the soy if your miso is salty. I usually skip it.", color: C.orange },
      { title: "Tomato pasta the slow way", body: "1 hr · serves 4\n\n800g tomatoes (canned San Marzano are fine) · 1 onion halved · 60g butter · big handful basil · 500g pasta.\n\nSimmer tomatoes, onion halves, and butter in a pot for 45 min. Fish out the onion. Toss with cooked bucatini and torn basil.\n\nNote: don't skip the butter. The butter is the whole thing.", color: C.rose },
      { title: "Weeknight dal", body: "30 min · serves 4\n\n1 cup red lentils · 1 onion · ginger · cumin · turmeric · 1 tomato · 4 cloves garlic · ghee.\n\nSimmer rinsed lentils with turmeric and salt. Sauté onion, ginger, cumin in ghee, add to lentils. Tarka of garlic in ghee on top right before serving.\n\nNote: pressure cook the lentils if you have one — it's even better that way.", color: C.amber },
      { title: "Banana oat cookies (3 ingredients)", body: "25 min · 12 cookies\n\n2 ripe bananas · 1 cup rolled oats · ½ cup chocolate chips.\n\nMash bananas, mix everything, scoop onto a tray, bake 180°C for 15 min.\n\nNote: I add a pinch of salt and cinnamon. Worth it.", color: C.yellow },
      { title: "Lazy chickpea curry", body: "25 min · serves 3\n\n1 can chickpeas · 1 can coconut milk · 1 onion · 2 tbsp curry paste · spinach · rice.\n\nFry onion, add paste, then both cans. Simmer 15 min. Wilt spinach in at the end. Serve over rice.\n\nNote: also great with tofu instead of chickpeas.", color: C.green },
    ],
  },
  {
    id: "travel-planner",
    name: "Travel Planner",
    description: "Plan a trip end-to-end: flights, stays, daily itinerary, packing, and a memory journal for after.",
    category: "Personal",
    layout: "stream",
    background: "linear-gradient(135deg, #dbeafe 0%, #cffafe 50%, #a7f3d0 100%)",
    emoji: "✈️",
    accent: "from-sky-500 to-cyan-500",
    tags: ["Planning", "Personal"],
    posts: [
      { title: "Trip: Tokyo + Kyoto · 10 days · April", body: "Travelers: 2 · Budget: SGD 4,000 each · Style: a bit of city, a bit of slow.", color: C.sky },
      { title: "Flights", body: "SQ → Tokyo Haneda · April 3, 13:30 dep → 21:00 arr (SQ12)\nKyoto → SIN · April 13, 18:00 dep → 23:55 arr (KIX, SQ619)\n\nConfirmation: ABCD1234", color: C.blue },
      { title: "Stays", body: "Tokyo (4 nights): Hotel Niwa Tokyo, Kanda — quiet, traditional\nKyoto (5 nights): Sowaka, Higashiyama — splurge, walking distance to shrines\n\nKeep printed copies of bookings.", color: C.lavender },
      { title: "Day 1 — Arrive Tokyo", body: "Land 21:00, Skyliner train, check in by 23:00. Convenience store dinner. Sleep early to fight jet lag.", color: C.green },
      { title: "Day 2 — Slow Tokyo", body: "Asakusa morning, walk Sumida river, ramen lunch in Yanaka, Ueno park afternoon, Shinjuku for dinner.", color: C.amber },
      { title: "Day 3 — Day in Kamakura", body: "Train at 9, Big Buddha first, then Hokokuji bamboo grove, sunset on Yuigahama beach, back by 21:00.", color: C.pink },
      { title: "Packing list", body: "• Passport + JR Pass voucher\n• Plug adapter (Japan = type A)\n• Walking shoes (we'll do 20km days)\n• Light rain jacket (April rain)\n• Pocket wifi rental confirmation\n• Small gifts from home (for hosts)\n• Painkillers, motion sickness, the usual", color: C.rose },
    ],
  },

  // ─────────── CREATIVE ───────────
  {
    id: "mood-board",
    name: "Mood Board",
    description: "Visual inspiration for a project, a brand, a room, or a vibe. Drop images, palettes, fonts, and references in one place.",
    category: "Creative",
    layout: "wall",
    background: "linear-gradient(135deg, #ddd6fe 0%, #f0abfc 33%, #67e8f9 66%, #6ee7b7 100%)",
    emoji: "🎨",
    accent: "from-fuchsia-500 to-pink-500",
    tags: ["Creative", "Brainstorming", "Showcase"],
    posts: [
      { title: "The brief", body: "Brand refresh for a small-batch coffee roastery. Three words: warm · honest · unhurried.", color: C.magenta },
      { title: "References", body: "Imagery feels like: golden hour light · old film grain · hands holding warm mugs · linen and wood textures.", color: C.amber },
      { body: "Add image references here — paste a URL or upload from your computer. Aim for variety, not consistency, at this stage.", color: C.lavender },
      { title: "Color palette", body: "#3a2417 deep coffee\n#c97b4a roasted amber\n#f5e6d3 warm cream\n#5d6e3f sage\n#1a1a1a near-black\n\nFeels grounded but not boring.", color: C.pink },
      { title: "Typography", body: "Display: a warm serif with a bit of soul (Cooper, Recoleta).\nBody: a clean humanist sans (Inter, Söhne).\n\nOpposites — but they should look like they grew up together.", color: C.sky },
      { title: "Anti-references", body: "Avoid: anything Starbucks-corporate · neon-y third-wave hipster · over-designed minimalism that loses the warmth.", color: C.rose },
    ],
  },
  {
    id: "vision-board",
    name: "Vision Board",
    description: "A snapshot of where you're heading. Goals, dreams, and the version of you that's becoming. Revisit quarterly.",
    category: "Creative",
    layout: "wall",
    background: "linear-gradient(135deg, #fef3c7 0%, #fed7aa 30%, #fca5a5 70%, #f472b6 100%)",
    emoji: "🌅",
    accent: "from-amber-500 to-rose-500",
    tags: ["Personal", "Reflection", "Creative"],
    posts: [
      { title: "This year, I want to…", body: "Build something I'm proud to show people. Not because they'll be impressed — because I'll be.", color: C.orange },
      { title: "Where I'll live", body: "Somewhere with a window I can throw open. A neighborhood with a coffee place I'm a regular at within six months. Walking distance to green.", color: C.sky },
      { title: "How I'll grow", body: "Read 24 books. Learn enough Japanese to order food without pointing. Run a 10K. Send three good emails a week to people I've lost touch with.", color: C.green },
      { title: "What I'll create", body: "Ship a side project a month. Write 12 blog posts. Make one short film. Bake bread until I don't have to look at the recipe anymore.", color: C.lavender },
      { title: "Who I'll be", body: "More patient. Less reactive. The kind of friend who shows up early and remembers birthdays. The kind of teammate people fight to work with.", color: C.pink },
      { title: "What I'll let go of", body: "The internal scoreboard. Comparing my chapter 2 to someone's chapter 20. The phone before bed. The yes-by-default.", color: C.rose },
    ],
  },
  {
    id: "inspiration-quotes",
    name: "Inspiration Quotes",
    description: "Words that move you, in one beautiful place. Re-read them on a hard day.",
    category: "Creative",
    layout: "wall",
    background: C.yellow,
    emoji: "✨",
    accent: "from-yellow-500 to-orange-500",
    tags: ["Creative", "Personal", "Showcase"],
    posts: [
      { body: "\"The best way out is always through.\"\n\n— Robert Frost", color: C.yellow },
      { body: "\"Do the thing you fear and the death of fear is certain.\"\n\n— Ralph Waldo Emerson", color: C.amber },
      { body: "\"What we do every day matters more than what we do once in a while.\"\n\n— Gretchen Rubin", color: C.lavender },
      { body: "\"Comparison is the thief of joy.\"\n\n— Theodore Roosevelt", color: C.pink },
      { body: "\"Be regular and orderly in your life so that you may be violent and original in your work.\"\n\n— Gustave Flaubert", color: C.green },
      { body: "\"You can't go back and change the beginning, but you can start where you are and change the ending.\"\n\n— C.S. Lewis", color: C.sky },
      { body: "\"Almost everything will work again if you unplug it for a few minutes — including you.\"\n\n— Anne Lamott", color: C.rose },
    ],
  },
  {
    id: "story-outline",
    name: "Story Outline",
    description: "A simple skeleton for a short story, screenplay, or novel chapter. Three acts, with a logline and theme to keep you honest.",
    category: "Creative",
    layout: "stream",
    background: C.lavender,
    emoji: "📝",
    accent: "from-violet-500 to-indigo-500",
    tags: ["Creative", "Planning"],
    posts: [
      { title: "Logline", body: "When her grandmother dies and leaves her a strange, hand-drawn map, a 14-year-old reluctant city girl spends a summer in a coastal village trying to follow it — and discovers her grandmother's biggest secret.", color: C.lavender },
      { title: "Theme", body: "What we inherit isn't just things — it's the unfinished stories of the people who loved us.", color: C.pink },
      { title: "Act 1 — Setup", body: "The world: Mira, 14, glued to her phone, mid-divorce parents, hates the idea of summer with grandma she barely knew.\n\nInciting incident: Grandma dies suddenly. The will leaves Mira a sealed envelope with a hand-drawn map of the village and one sentence: \"Walk it in order.\"", color: C.green },
      { title: "Act 2 — Confrontation", body: "She arrives, grumpy. Starts the map only because there's no wifi. Each location reveals a small piece of her grandmother's youth — a sweetheart, a betrayal, a child given up.\n\nMidpoint twist: the child given up was Mira's mother. Mira's mother doesn't know.\n\nLowest point: Mira finds a letter from her grandmother to that lost child, never sent. She has to decide: deliver it, or let her mother live without knowing.", color: C.amber },
      { title: "Act 3 — Resolution", body: "Climax: Mira gives her mother the letter. They read it together at the lighthouse — the last point on the map.\n\nAftermath: Mira's mother is shaken but lighter. They walk back to the village together. Mira keeps the map.\n\nLanding: Mira posts a photo of the map with the caption: \"Things I inherited.\"", color: C.sky },
    ],
  },
  {
    id: "color-palette",
    name: "Color Palette",
    description: "Lock in a five-color palette for a brand, a room, or a design. With hex codes and the why behind each pick.",
    category: "Creative",
    layout: "grid",
    background: C.white,
    emoji: "🎨",
    accent: "from-pink-500 to-violet-500",
    tags: ["Creative", "Showcase"],
    posts: [
      { title: "Primary · #7c3aed", body: "Violet 600. The hero. Used for the logo and primary actions. Energetic but not childish — sits between blue and red on the spectrum so it inherits both reliability and warmth.", color: "#ede9fe" },
      { title: "Accent · #ec4899", body: "Pink 500. The CTA color. Used sparingly — Create buttons, the moment you want someone to act. Pairs with the violet for a confident, modern feel.", color: "#fce7f3" },
      { title: "Background · #fafaf9", body: "Stone 50. Warm off-white, easier on the eyes than pure white. Lets the colorful posts shine without competing.", color: "#fafaf9" },
      { title: "Text · #0f172a", body: "Slate 900. Near-black, not pure black — softer at small sizes, equally readable. Body, headings, everything.", color: "#e2e8f0" },
      { title: "Mood", body: "Three words to describe this palette: bold · warm · honest.\n\nUse with: a clean humanist sans like Inter, generous whitespace, and rounded-2xl corners on cards.", color: "#fed7aa" },
    ],
  },
  {
    id: "before-after",
    name: "Before & After",
    description: "Compare two states side-by-side: before and after a change, an experiment, a renovation, a haircut. Anything you can document.",
    category: "Creative",
    layout: "grid",
    background: C.green,
    emoji: "🔁",
    accent: "from-green-500 to-emerald-500",
    tags: ["Showcase", "Reflection", "Creative"],
    posts: [
      { title: "Before — the old onboarding", body: "12 fields on signup. 4 emails in the first week. 23-minute median time to first action. Activation rate: 31%.", color: C.rose },
      { title: "After — the redesigned onboarding", body: "3 fields on signup, the rest progressive. 1 email focused on the next action. 11-minute median time to first action. Activation rate: 49%.", color: C.green },
      { title: "What we changed", body: "Cut everything that wasn't essential to first value. Moved profile fields to a later \"complete your profile\" prompt. Re-wrote the first email to point to one specific action.", color: C.amber },
      { title: "What we learned", body: "Friction in onboarding compounds. Removing one field doesn't just save 10 seconds — it removes a moment of doubt where users drop off. Defaults matter more than options.", color: C.lavender },
    ],
  },
];

export const TEMPLATE_CATEGORIES: TemplateCategory[] = ["Education", "Work", "Personal", "Creative"];

export function getTemplate(id: string) {
  return TEMPLATES.find((t) => t.id === id);
}

export function getRelatedTemplates(id: string, limit = 4) {
  const t = getTemplate(id);
  if (!t) return [];
  const sameCategory = TEMPLATES.filter((x) => x.id !== id && x.category === t.category);
  const others = TEMPLATES.filter((x) => x.id !== id && x.category !== t.category);
  return [...sameCategory, ...others].slice(0, limit);
}
